-- Migration 010: Tamil language columns on issues
-- Applied as part of v4 Tamil UI feature.
-- cluster_issues.py back-fills these via a Gemini translate pass on first run.

ALTER TABLE issues
  ADD COLUMN IF NOT EXISTS title_ta    TEXT,
  ADD COLUMN IF NOT EXISTS summary_ta  TEXT;

COMMENT ON COLUMN issues.title_ta   IS 'Tamil translation of title, generated by Gemini at cluster time. NULL until back-fill runs.';
COMMENT ON COLUMN issues.summary_ta IS 'Tamil translation of summary, generated by Gemini at cluster time. NULL until back-fill runs.';

-- RLS: anon role already has SELECT on issues (migration 008). No new policy needed.
