ALTER TABLE tweets
ADD COLUMN IF NOT EXISTS translated_content TEXT;

COMMENT ON COLUMN tweets.translated_content IS
  'English translation of tweet content, generated by Gemini Flash at categorization time.
   NULL if tweet is already in English or translation failed.';
